// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAiri(arg1) {
  return window['go']['main']['App']['AskAiri'](arg1);
}

export function Calculate(arg1, arg2) {
  return window['go']['main']['App']['Calculate'](arg1, arg2);
}

export function ClearConversationHistory() {
  return window['go']['main']['App']['ClearConversationHistory']();
}

export function GetConversationHistory() {
  return window['go']['main']['App']['GetConversationHistory']();
}

export function GetDatabaseContents() {
  return window['go']['main']['App']['GetDatabaseContents']();
}

export function GetRunningApps() {
  return window['go']['main']['App']['GetRunningApps']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendUserMessage(arg1) {
  return window['go']['main']['App']['SendUserMessage'](arg1);
}
