// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AskAiri(arg1:string):Promise<string>;

export function Calculate(arg1:number,arg2:number):Promise<number>;

export function ClearConversationHistory():Promise<void>;

export function GetConversationHistory():Promise<Array<main.ConversationMessage>>;

export function GetDatabaseContents():Promise<string>;

export function GetRunningApps():Promise<Array<main.RunningApp>>;

export function Greet(arg1:string):Promise<string>;

export function SendUserMessage(arg1:string):Promise<string>;
